version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
  nodered:
    image: nodered/node-red:latest
    restart: always
    network_mode: host
    volumes:
      - ./config/nodered:/data
    ports:
      - "1880:1880"
    user: "1000"

  portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer/:/data
    ports:
      - 9000:9000
