version: "3"

services:
  tesberry-bridge:
    build: ./packages/bridge
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - VEHICLE_CAN=can0

  tesberry-ui:
    build: ./packages/ui
    restart: always
    network_mode: host
    environment:
      - PORT=80

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001

  savvycan-mqtt:
    build: ./packages/savvycan-mqtt
    restart: "no"
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - CHANNEL=can0
      - MQTT_HOST=localhost
      - MQTT_PORT=1883

  carplay:
    build: ./packages/carplay
    restart: "no"
    ports:
      - 3001:3001
    environment:
      - LIBUSB_DEBUG=9
    volumes:
      - /dev/bus/usb:/dev/bus/usb

  nodered:
    image: nodered/node-red:latest
    restart: always
    network_mode: host
    volumes:
      - ./config/nodered:/data
    ports:
      - 1880:1880
    user: "1000"

  portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer/:/data
    ports:
      - 9000:9000
